/*Generated by WaveMaker Studio*/
package com.test01.services.globalweather;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.11
 * 2017-11-03T06:04:54.574Z
 * Generated source version: 2.7.11
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET", name = "GlobalWeatherSoap")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GlobalWeatherSoap {

    /**
     * Get all major cities by country name(full / part).
     */
    @WebMethod(operationName = "GetCitiesByCountry", action = "http://www.webserviceX.NET/GetCitiesByCountry")
    @WebResult(name = "GetCitiesByCountryResponse", targetNamespace = "http://www.webserviceX.NET", partName = "parameters")
    public GetCitiesByCountryResponse getCitiesByCountry(
        @WebParam(partName = "parameters", name = "GetCitiesByCountry", targetNamespace = "http://www.webserviceX.NET")
        GetCitiesByCountry parameters
    );

    /**
     * Get weather report for all major cities around the world.
     */
    @WebMethod(operationName = "GetWeather", action = "http://www.webserviceX.NET/GetWeather")
    @WebResult(name = "GetWeatherResponse", targetNamespace = "http://www.webserviceX.NET", partName = "parameters")
    public GetWeatherResponse getWeather(
        @WebParam(partName = "parameters", name = "GetWeather", targetNamespace = "http://www.webserviceX.NET")
        GetWeather parameters
    );
}
