/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

package com.test01.services.globalweather.services;
import com.test01.services.globalweather.*;
import java.util.List;

import com.wavemaker.runtime.soap.util.SoapSettingsResolver;
import com.wavemaker.runtime.soap.SoapServiceSettings;

import org.springframework.stereotype.Service;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import javax.xml.ws.BindingProvider;



@Service
public class GlobalWeatherService{

    @Autowired
    @Qualifier("GlobalWeatherSoapServiceSettings")
    private SoapServiceSettings soapServiceSettings;


	public GetCitiesByCountryResponse getCitiesByCountry(  com.test01.services.globalweather.GetCitiesByCountry parameters )
	          {
 	    GlobalWeather globalweather = new GlobalWeather();
 GlobalWeatherSoap globalweathersoap = globalweather.getGlobalWeatherSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)globalweathersoap, soapServiceSettings);
 return globalweathersoap.getCitiesByCountry(parameters );
	}

	public GetWeatherResponse getWeather(  com.test01.services.globalweather.GetWeather parameters )
	          {
 	    GlobalWeather globalweather = new GlobalWeather();
 GlobalWeatherSoap globalweathersoap = globalweather.getGlobalWeatherSoap();
 SoapSettingsResolver.setBindingProperties((BindingProvider)globalweathersoap, soapServiceSettings);
 return globalweathersoap.getWeather(parameters );
	}
}
