/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
package com.test01.services.globalweather.controller;

import com.test01.services.globalweather.services.GlobalWeatherService;
import com.test01.services.globalweather.GetCitiesByCountry;
import java.lang.String;
import com.test01.services.globalweather.GetCitiesByCountryResponse;
import com.test01.services.globalweather.GetWeather;
import com.test01.services.globalweather.GetWeatherResponse;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.MediaType;
import org.springframework.beans.factory.annotation.Autowired;

@RestController
@RequestMapping(value = "/globalWeather")
public class GlobalWeatherController {

    @Autowired
    private GlobalWeatherService globalWeatherService;

    @RequestMapping(value = "/citiesBycountry", method = RequestMethod.GET)
    public GetCitiesByCountryResponse getCitiesByCountry(@RequestParam(value = "countryName", required = false) String countryName) {
        GetCitiesByCountry parameters = new GetCitiesByCountry();
        parameters.setCountryName(countryName);
        return globalWeatherService.getCitiesByCountry(parameters);
    }

    @RequestMapping(value = "/weather", method = RequestMethod.GET)
    public GetWeatherResponse getWeather(@RequestParam(value = "cityName", required = false) String cityName, @RequestParam(value = "countryName", required = false) String countryName) {
        GetWeather parameters = new GetWeather();
        parameters.setCityName(cityName);
        parameters.setCountryName(countryName);
        return globalWeatherService.getWeather(parameters);
    }
}
